# Generated by Django 4.2.16 on 2024-11-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_id_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
