# Generated by Django 4.2.16 on 2024-10-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="chats",
            name="username_1",
            field=models.CharField(default="def", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chats",
            name="username_2",
            field=models.CharField(default="11", max_length=150),
            preserve_default=False,
        ),
    ]
