# Generated by Django 4.2.16 on 2024-11-25 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messaging", "0006_alter_chats_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chats",
            name="participants",
            field=models.ManyToManyField(
                related_name="chats", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
