# Generated by Django 4.2.16 on 2024-11-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0007_alter_chats_participants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messages",
            name="receiver",
        ),
    ]
