# Generated by Django 4.2.16 on 2024-11-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0009_rename_send_time_messages_sent_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="chats",
            name="chat_name",
            field=models.CharField(default="", max_length=225),
            preserve_default=False,
        ),
    ]
