# Generated by Django 4.2.16 on 2024-10-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Test_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("msg", models.TextField()),
                ("sent_time", models.DateTimeField(auto_now_add=True)),
                ("sender", models.CharField(max_length=100)),
                ("receiver", models.CharField(max_length=100)),
            ],
        ),
    ]
